---
development:
  cloud_name: Rails.application.credentials.dig(:cloudinary_cloud_name)
  api_key: Rails.application.credentials.dig(:cloudinary_api_key)
  api_secret: Rails.application.credentials.dig(:cloudinary_api_secret)
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: Rails.application.credentials.dig(:cloudinary_cloud_name)
  api_key: Rails.application.credentials.dig(:cloudinary_api_key)
  api_secret: Rails.application.credentials.dig(:cloudinary_api_secret)
  enhance_image_tag: true
  static_file_support: true